import { useEffect, useRef, useState } from 'react';
import { ArrowRight, ArrowUpRight, BarChart3, CalendarDays, ChevronLeft, ChevronRight, Coins, Eye, FileCheck2, Hand, Heart, MapPin, Megaphone, MoreHorizontal, RefreshCw, Star, Ticket, Users, X } from 'lucide-react';
import { apiUrl, getSession } from '../../api';
import { useRouter } from '../../router';
import { useManagerDashboard } from '../../layout/ManagerShell';

const compact = value => new Intl.NumberFormat('en', { notation: 'compact', maximumFractionDigits: 1 }).format(value || 0);
const date = value => new Date(value).toLocaleString(undefined, { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' });
const status = event => event.status === 'draft' ? 'Draft' : event.status !== 'published' ? event.status : new Date(event.ends_at) <= new Date() ? 'Ended' : new Date(event.starts_at) <= new Date() ? 'Live' : 'Upcoming';
function EventPhoto({ event }) {
  const [failed, setFailed] = useState(false);
  const photo = event.media?.find(item => item.type === 'image')?.url;
  const src = photo?.startsWith('/storage/') ? apiUrl.replace(/\/api\/v1$/, '') + photo : photo;
  return src && !failed ? <img src={src} alt="" onError={() => setFailed(true)} /> : <span className="md-event-placeholder"><CalendarDays size={25} /></span>;
}
function BookingChart({ activity }) {
  const [hover, setHover] = useState(null);
  const max = Math.max(1, ...activity.map(day => day.tickets));
  const points = activity.map((day, index) => [36 + index / Math.max(1, activity.length - 1) * 304, 142 - day.tickets / max * 118]);
  const line = points.map(([x, y]) => `${x},${y}`).join(' ');
  return <div className="md-chart"><svg viewBox="0 0 355 178" role="img" aria-label="Confirmed tickets booked per day"><defs><linearGradient id="manager-booking-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#9035ff" stopOpacity=".22" /><stop offset="100%" stopColor="#9035ff" stopOpacity=".02" /></linearGradient></defs>{[0, .5, 1].map(fraction => <g key={fraction}><line x1="36" x2="340" y1={142 - fraction * 118} y2={142 - fraction * 118} stroke="#eceaf5" /><text x="2" y={146 - fraction * 118}>{compact(max * fraction)}</text></g>)}{points.length > 0 && <><polygon points={`36,142 ${line} 340,142`} fill="url(#manager-booking-fill)" /><polyline points={line} fill="none" stroke="#882aff" strokeWidth="2.5" strokeLinejoin="round" />{points.map(([x, y], index) => <circle key={activity[index].date} cx={x} cy={y} r="5" fill={hover === index ? '#882aff' : 'transparent'} tabIndex="0" aria-label={`${activity[index].date}: ${activity[index].tickets} tickets`} onFocus={() => setHover(index)} onBlur={() => setHover(null)} onMouseEnter={() => setHover(index)} onMouseLeave={() => setHover(null)}><title>{activity[index].date}: {activity[index].tickets} tickets</title></circle>)}</>}<text x="36" y="168">{activity[0]?.date.slice(5)}</text><text x="340" y="168" textAnchor="end">{activity.at(-1)?.date.slice(5)}</text></svg><div className="md-chart-caption" aria-live="polite">{hover !== null && activity[hover] ? `${activity[hover].date}: ${activity[hover].tickets} tickets` : 'Confirmed bookings'}</div></div>;
}

export default function ManagerDashboard() {
  const { navigate, path } = useRouter();
  const { data, loading, error, search, city, retry } = useManagerDashboard();
  const [tab, setTab] = useState('Upcoming');
  const [period, setPeriod] = useState(30);
  const [expanded, setExpanded] = useState(false);
  const [page, setPage] = useState(0);
  const [selected, setSelected] = useState(null);
  const dialog = useRef(null);
  useEffect(() => { setPage(0); }, [tab, search, city, expanded]);
  useEffect(() => { if (selected) dialog.current?.showModal(); }, [selected]);
  const all = data?.events || [];
  const matches = all.filter(event => `${event.name} ${event.venue?.name || ''} ${event.location_name || ''}`.toLowerCase().includes(search.trim().toLowerCase()));
  const groups = { Upcoming: matches.filter(event => status(event) === 'Upcoming').sort((a, b) => new Date(a.starts_at) - new Date(b.starts_at)), Live: matches.filter(event => status(event) === 'Live'), Drafts: matches.filter(event => status(event) === 'Draft'), Past: matches.filter(event => status(event) === 'Ended') };
  // Keep the dashboard compact initially, then expose every matching event on demand.
  const size = expanded || path === '/manager/events' ? Math.max(1, groups[tab].length) : 3;
  const currentPage = Math.min(page, Math.max(0, Math.ceil(groups[tab].length / size) - 1));
  const rows = groups[tab].slice(currentPage * size, (currentPage + 1) * size);
  const activity = (data?.booking_activity || []).slice(-period);
  const booked = activity.reduce((sum, day) => sum + day.tickets, 0);
  const stats = data?.summary;
  const revenue = Object.entries(stats?.revenue || {}).map(([currency, value]) => `${currency === 'TZS' ? 'TSh' : currency} ${compact(value)}`).join(' / ') || 'TSh 0';
  const metrics = [[Eye, 'Event views', compact(stats?.views), 'purple', 'Across the platform'], [Ticket, 'Tickets sold', compact(stats?.tickets), 'pink', 'All-time sales'], [CalendarDays, 'Upcoming events', stats?.upcoming || 0, 'amber', 'Published & scheduled'], [Coins, 'Event revenue', revenue, 'cyan', 'All-time event revenue']];
  const quick = data?.quick_stats;
  const quickStats = [[MapPin, 'Venues', quick?.venues || 0, 'cyan'], [Users, 'Hosts', compact(quick?.hosts), 'purple'], [Heart, 'Event likes', compact(quick?.likes), 'pink'], [Star, 'Event ratings', quick?.rating ?? '-', 'amber']];
  const countBy = key => Object.entries(all.reduce((counts, event) => { const value = key(event); if (value) counts[value] = (counts[value] || 0) + 1; return counts; }, {})).sort((a, b) => b[1] - a[1])[0];
  const topCity = countBy(event => event.venue?.city);
  const topCategory = countBy(event => event.category);
  const upcoming = all.filter(event => status(event) === 'Upcoming').sort((a, b) => new Date(a.starts_at) - new Date(b.starts_at));
  const closeDialog = () => { dialog.current?.close(); setSelected(null); };
  return <div className="manager-dashboard">
    <section className="md-hero"><div><h1>Welcome back, {getSession()?.user?.name?.split(' ')[0] || 'admin'} <Hand size={30} aria-hidden="true" /></h1><p>Discover, support and grow your community - all in one place.</p></div><span className="md-motto" aria-hidden="true">Good<br />Vibes<br />Only!</span><blockquote>Events bring people together. Let's make this weekend amazing! <Star size={19} /></blockquote></section>
    {error ? <section className="md-state" role="alert"><h2>Dashboard unavailable</h2><p>{error}</p><button className="md-primary" onClick={retry}><RefreshCw size={17} />Try again</button></section> : loading ? <section className="md-state" role="status"><RefreshCw className="md-loading" size={26} /><p>Loading your dashboard...</p></section> : <>
      <div className="md-workspace"><div className="md-main-column">
        <section className="md-metrics" aria-label="Platform totals">{metrics.map(([Icon, label, value, tone, note]) => <article className="md-metric" key={label}><span className={`md-icon ${tone}`}><Icon size={25} /></span><p>{label}</p><strong>{value}</strong><small>{note}</small></article>)}</section>
        <div className="md-middle"><section className="md-panel md-events"><div className="md-heading"><h2>Platform Events</h2><button onClick={() => setExpanded(value => !value)}>{expanded ? 'Show less' : 'View all events'} <ChevronRight size={15} /></button></div><div className="md-tabs" aria-label="Event status">{Object.entries(groups).map(([label, items]) => <button key={label} className={label === tab ? 'active' : ''} aria-pressed={label === tab} onClick={() => setTab(label)}>{label} ({items.length})</button>)}</div><div aria-live="polite">{rows.map(event => <article className="md-event" key={event.id}><EventPhoto event={event} /><div className="md-event-info"><button onClick={() => setSelected(event)}>{event.name}</button><span><CalendarDays size={13} />{date(event.starts_at)}</span><span><MapPin size={13} />{event.venue?.name || event.location_name || 'Location pending'}</span></div><span className={`md-status ${status(event).toLowerCase()}`}>{status(event)}</span><div className="md-tickets"><strong>{compact(event.tickets_sold)}</strong><small>tickets sold</small></div><button className="md-more" title="Event details" aria-label={`View ${event.name}`} onClick={() => setSelected(event)}><MoreHorizontal size={20} /></button></article>)}{!rows.length && <div className="md-empty"><CalendarDays size={30} /><h3>{search ? 'No matching events' : `No ${tab.toLowerCase()} events`}</h3><p>{search ? 'Try another event or venue name.' : 'Events will appear here as the community grows.'}</p></div>}</div>{groups[tab].length > size && <div className="md-pagination"><span>{currentPage * size + 1}-{Math.min((currentPage + 1) * size, groups[tab].length)} of {groups[tab].length}</span><button aria-label="Previous events" disabled={currentPage === 0} onClick={() => setPage(currentPage - 1)}><ChevronLeft size={17} /></button><button aria-label="Next events" disabled={(currentPage + 1) * size >= groups[tab].length} onClick={() => setPage(currentPage + 1)}><ChevronRight size={17} /></button></div>}</section>
        <section className="md-panel md-insights"><div className="md-heading"><h2>Booking Insights</h2><select aria-label="Booking activity period" value={period} onChange={event => setPeriod(Number(event.target.value))}><option value={30}>Last 30 days</option><option value={7}>Last 7 days</option></select></div><div className="md-chart-total"><strong>{booked.toLocaleString()}</strong><span>Tickets booked</span></div><BookingChart activity={activity} />{[[topCity, 'Top event location', 'purple'], [topCategory, 'Most hosted category', 'pink']].map(([item, label, tone]) => <div className={`md-insight ${tone}`} key={label}><small>{label}</small><strong>{item?.[0] || 'No events yet'}</strong><progress value={item?.[1] || 0} max={Math.max(1, all.length)} aria-label={label} /><span>{Math.round((item?.[1] || 0) / Math.max(1, all.length) * 100)}%</span></div>)}</section></div>
      </div><aside className="md-side-column"><div className="md-quick-actions"><button className="md-primary" onClick={() => navigate('/manager/venues')}><FileCheck2 size={20} />Review Venues{data.pending.venues > 0 && <b>{data.pending.venues}</b>}</button><button onClick={() => navigate('/manager/hosts')}><Users size={21} />Host Approvals</button><button onClick={() => navigate('/manager/events')}><CalendarDays size={21} />Manage Events</button><button onClick={() => navigate('/manager/advertising')}><Megaphone size={21} />Advertising</button></div><section className="md-panel md-upcoming"><div className="md-heading"><h2>Coming Up Next</h2><button onClick={() => { setTab('Upcoming'); setExpanded(true); }}>See all</button></div>{upcoming.slice(0, 2).map(event => <button className="md-next-event" key={event.id} onClick={() => setSelected(event)}><EventPhoto event={event} /><span><strong>{event.name}</strong><small>{date(event.starts_at)}</small><small><MapPin size={12} />{event.venue?.name || event.location_name}</small></span></button>)}{!upcoming.length && <p className="md-side-empty">No upcoming events yet.</p>}</section><section className="md-panel md-quick-stats"><div className="md-heading"><h2>Quick Stats</h2></div>{quickStats.map(([Icon, label, value, tone]) => <div key={label}><span className={`md-icon ${tone}`}><Icon size={17} /></span><span>{label}</span><strong>{value}</strong></div>)}</section></aside></div>
      <section className="md-bottom-links" aria-label="Platform management">{[[Users, 'Grow your community', 'Hosts & members', '/manager/users', 'purple'], [CalendarDays, 'Manage your experiences', 'Events', '/manager/events', 'cyan'], [Heart, 'Bring experiences to life', 'Community advertising', '/manager/advertising', 'pink']].map(([Icon, title, caption, to, tone]) => <button key={to} onClick={() => navigate(to)}><span className={`md-icon ${tone}`}><Icon size={30} /></span><span><strong>{title}</strong><small>{caption}</small></span><ArrowUpRight size={17} /></button>)}</section>
    </>}
    <dialog ref={dialog} className="md-dialog" onCancel={closeDialog} onClick={event => { if (event.target === dialog.current) closeDialog(); }} onClose={() => setSelected(null)} aria-labelledby="manager-event-title">{selected && <><div className="md-heading"><h2 id="manager-event-title">{selected.name}</h2><button className="manager-icon" aria-label="Close event details" onClick={closeDialog}><X size={21} /></button></div><div className="md-dialog-photo"><EventPhoto event={selected} /></div><span className={`md-status ${status(selected).toLowerCase()}`}>{status(selected)}</span><dl><dt>Venue</dt><dd>{selected.venue?.name || selected.location_name || '-'}</dd><dt>Starts</dt><dd>{date(selected.starts_at)}</dd><dt>Ends</dt><dd>{date(selected.ends_at)}</dd><dt>Tickets sold</dt><dd>{Number(selected.tickets_sold || 0).toLocaleString()}</dd><dt>Views</dt><dd>{Number(selected.views_count || 0).toLocaleString()}</dd></dl>{selected.description && <p>{selected.description}</p>}{selected.status === 'published' && <button className="md-primary" onClick={() => { const id = selected.id; closeDialog(); navigate('/events/' + id); }}>Open event <ArrowRight size={17} /></button>}</>}</dialog>
  </div>;
}
