import { Activity, BadgeCheck, CalendarDays, CircleDollarSign, CreditCard, FileCheck2, Megaphone, MapPin, Sparkles, Store, Eye } from 'lucide-react'
import { useRouter } from '../../router'
import { hosts } from '../../data/mockData'
import { Badge, MetricCard, PageHeading, SectionHeader } from '../../components/ui'

function ActivityItem({ icon: Icon, tone, title, text, time }) { return <div className="activity-item"><span className={`activity-icon ${tone}`}><Icon size={17} /></span><div><strong>{title}</strong><p>{text}</p></div><small>{time}</small></div> }

export default function ManagerOverviewPage() {
  const { navigate } = useRouter()
  return <>
    <PageHeading badge={<Badge tone="purple"><Sparkles size={13} /> Sunday, 2 August</Badge>} title="Good evening, Duncan." description="Here’s what is happening across the Vibfy ecosystem today."><button className="primary-button" onClick={() => navigate('/manager/hosts')}><FileCheck2 size={18} />Review applications</button></PageHeading>
    <div className="metrics-grid"><MetricCard icon={Store} label="Active hosts" value="148" delta="12.4%" tone="purple" /><MetricCard icon={CalendarDays} label="Live events" value="64" delta="8.2%" tone="pink" /><MetricCard icon={CircleDollarSign} label="Monthly revenue" value="TSh 18.4M" delta="16.8%" tone="amber" /><MetricCard icon={Megaphone} label="Active adverts" value="23" delta="5.1%" tone="cyan" /></div>
    <div className="dashboard-grid"><section className="panel approvals-panel"><SectionHeader title="Host applications" subtitle="Businesses waiting for review" action="View all" onAction={() => navigate('/manager/hosts')} /><div className="application-list">{hosts.slice(0, 3).map((host, index) => <div className="application-row" key={host.name}><div className={`business-avatar color-${index}`}>{host.initials}</div><div className="application-info"><strong>{host.name}</strong><span>{host.owner} · {host.type}</span></div><div className="application-location"><MapPin size={14} />{host.location}</div><Badge tone={host.status === 'New' ? 'green' : 'amber'}>{host.status}</Badge><button className="round-arrow" onClick={() => navigate('/manager/hosts')}><Eye size={15} /></button></div>)}</div></section>
      <section className="panel revenue-panel"><SectionHeader title="Revenue overview" subtitle="Subscriptions & advertising" /><div className="revenue-value"><strong>TSh 18.4M</strong><Badge tone="green">+16.8%</Badge></div><div className="chart-bars">{[38, 52, 43, 66, 58, 78, 69, 91, 74, 88, 96, 84].map((h, i) => <span key={i} style={{ height: `${h}%` }} className={i === 10 ? 'highlight' : ''} />)}</div><div className="chart-labels"><span>Sep</span><span>Dec</span><span>Mar</span><span>Jun</span><span>Aug</span></div></section></div>
    <div className="dashboard-grid lower"><section className="panel"><SectionHeader title="Platform activity" subtitle="Latest updates across Vibfy" /><div className="activity-list"><ActivityItem icon={BadgeCheck} tone="green" title="Host approved" text="Kibo Rooftop was approved by you" time="8 min" /><ActivityItem icon={Megaphone} tone="pink" title="Campaign launched" text="Summer Sundowner started running" time="34 min" /><ActivityItem icon={CreditCard} tone="purple" title="Subscription renewed" text="Themi Living Garden renewed Pro" time="1 hr" /><ActivityItem icon={CalendarDays} tone="amber" title="New event published" text="Arusha Afro Night is now live" time="2 hrs" /></div></section>
      <section className="panel plan-split"><SectionHeader title="Subscriptions" subtitle="Active plans distribution" /><div className="donut"><div><strong>148</strong><span>Hosts</span></div></div><div className="legend"><p><i className="pro" />Pro plan <strong>72</strong></p><p><i className="growth" />Growth <strong>48</strong></p><p><i className="starter" />Starter <strong>28</strong></p></div></section></div>
  </>
}
