import { ArrowDown, ArrowRight, ArrowUpRight, CalendarDays, Check, MapPin, Music2, Sparkles, Store, Users } from 'lucide-react'
import { useState } from 'react'
import { useRouter } from '../router'
import AppDownloadBadges from '../components/AppDownloadBadges'
import CommunityHeader, { CommunityLink } from '../community/CommunityHeader'
import { EventCollection } from '../community/EventDiscovery'
import CommunityFooter from '../community/CommunityFooter'

const experiences = [
  ['Nights with a little more soul.', 'Music & nightlife', 'afro-night.png', Music2],
  ['Good company. Great spaces.', 'Venues & gatherings', 'venue-garden.png', Store],
  ['The kind of live you feel.', 'Live performances', 'live-band.png', Users],
]
export default function LandingPage() {
  const { navigate } = useRouter()
  const [category, setCategory] = useState('All experiences')
  const go = (event, path) => { event.preventDefault(); navigate(path) }
  return <div className="vf-landing">
    <a className="vf-skip" href="#main-content">Skip to content</a>
    <CommunityHeader />
    <main id="main-content">
      <section className="vf-hero"><div className="vf-hero-copy"><span className="vf-eyebrow"><i /> GO OUT. FIND YOUR PEOPLE. FEEL THE VIBE.</span><h1>Your next<br /><em>great night</em><br />starts here.</h1><p>Live music, hidden gems, and the nights you wish would never end. Make room for more real-life moments with Vibfy.</p><div className="vf-actions"><CommunityLink className="vf-button" to="/discover">Find your vibe <ArrowUpRight size={19} /></CommunityLink><a className="vf-text-link" href="#get-the-app">Get the app <ArrowDown size={17} /></a></div><AppDownloadBadges /><div className="vf-hero-note"><span><MapPin size={15} /> ROOTED IN EAST AFRICA</span><span>Made for your next big thing.</span></div></div><div className="vf-hero-art"><img className="vf-main-photo" src="/images/afro-night.png" alt="Friends enjoying an atmospheric night out" fetchPriority="high" /><div className="vf-photo-shade" /><span className="vf-photo-label"><i /> THE NIGHT IS YOURS</span><div className="vf-photo-caption"><span>MAKE ROOM FOR</span><h2>A little more<br />“you had to be there.”</h2><span><MapPin size={15} /> Nairobi, Kenya</span></div><div className="vf-sticker"><Sparkles size={23} /><span>Real places.<br />Real connection.</span></div><div className="vf-inset"><img src="/images/venue-garden.png" alt="A lush outdoor venue ready to welcome guests" /><span>Your space. Their new favourite. <ArrowUpRight size={16} /></span></div></div></section>
      <div className="vf-ribbon"><span>Discover something different.</span><Sparkles /><span>Go where you feel alive.</span><Sparkles /><span>Find your kind of people.</span></div>
      <section className="vf-section community-home-events"><div className="vf-section-heading"><div><span className="vf-eyebrow">GOOD TIMES ARE HAPPENING</span><h2>Find something worth showing up for.</h2></div><CommunityLink className="vf-text-link" to="/discover">Explore all experiences <ArrowUpRight size={18} /></CommunityLink></div><EventCollection compact /></section>
      <section className="vf-section" id="experiences"><div className="vf-section-heading"><div><span className="vf-eyebrow">ALL KINDS OF GOOD TIMES</span><h2>There's a vibe for that.</h2></div><p>From intimate garden gatherings to nights that turn into stories. Make yours happen.</p></div><div className="vf-category-tabs" role="group" aria-label="Filter experience categories">{['All experiences', ...experiences.map(item => item[1])].map(item => <button key={item} aria-pressed={category === item} className={category === item ? 'active' : ''} onClick={() => setCategory(item)}>{item === 'All experiences' && <Sparkles size={15} />}{item}</button>)}</div><div className="vf-experiences" aria-live="polite">{experiences.filter(item => category === 'All experiences' || item[1] === category).map(([title, category, image, Icon]) => <a key={category} className="vf-experience" href={category === 'Music & nightlife' ? '/discover?category=Nightlife' : category === 'Live performances' ? '/discover?category=Music' : '/discover'} onClick={e => go(e, e.currentTarget.getAttribute('href'))}><div className="vf-experience-image"><img src={`/images/${image}`} alt={category} loading="lazy" /><span><Icon size={15} />{category}</span><i><ArrowUpRight size={21} /></i></div><h3>{title}</h3><span className="vf-experience-link">Explore experiences on Vibfy <ArrowRight size={15} /></span></a>)}</div></section>
      <section className="vf-app-section" id="get-the-app">
        <div className="vf-app-copy"><span className="vf-eyebrow"><Sparkles size={16} /> GOOD TIMES, RIGHT IN YOUR POCKET</span><h2>Less scrolling.<br /><em>More showing up.</em></h2><p>Make your next plan a good one. Take Vibfy with you and keep your world of experiences close.</p><div className="vf-app-perks"><span><Music2 size={18} /> Find your kind of night</span><span><MapPin size={18} /> Explore places around you</span><span><Users size={18} /> Make memories together</span></div><AppDownloadBadges /></div>
        <div className="vf-phone-scene"><span className="vf-app-orbit" /><span className="vf-phone-note"><Sparkles size={18} /> Plans worth leaving home for.</span><div className="vf-phone" aria-label="Illustrative Vibfy app preview"><div className="vf-phone-top"><span>9:41</span><span className="vf-phone-island" /><span aria-hidden="true">&#8226;&#8226;&#8226;</span></div><div className="vf-phone-content"><div className="vf-phone-brand"><img className="vibfy-brand-image" src="/images/vibfy-logo.png" alt="Vibfy" width="1280" height="1280" /><span><MapPin size={12} /> Nairobi</span></div><h3>Go find<br />your <em>good time.</em></h3><div className="vf-phone-chips"><span>For you</span><span>Music</span><span>Outdoors</span></div><div className="vf-phone-event"><img src="/images/amapiano-night.png" alt="A vibrant music night in the Vibfy app concept" loading="lazy" /><span>FIND YOUR RHYTHM</span><div><small>MUSIC & NIGHTLIFE</small><strong>After dark. All energy.</strong><span><MapPin size={11} /> Nairobi, Kenya</span></div></div><div className="vf-phone-mini"><img src="/images/venue-garden.png" alt="Garden gathering" loading="lazy" /><div><small>A CHANGE OF SCENERY</small><strong>Your new favourite spot</strong><span>Spaces with a little soul.</span></div><ArrowUpRight size={17} /></div><div className="vf-phone-bottom"><span><Sparkles size={18} />Discover</span><span><CalendarDays size={18} />Experiences</span><span><Users size={18} />Profile</span></div></div></div><span className="vf-preview-label">A little look at the Vibfy experience &middot; App concept</span></div>
      </section>
      <section className="vf-section vf-how" id="how-it-works"><div className="vf-how-photo"><img src="/images/live-band.png" alt="Musicians bringing a live performance to life" loading="lazy" /><span>Less organising.<br /><em>More moments like this.</em></span></div><div><span className="vf-eyebrow">FROM IDEA TO “I'M THERE”</span><h2>Your next chapter<br />starts with a hello.</h2><ol>{[['Make yourself at home', 'Join Vibfy with one account for discovering, attending, and hosting.'], ['Find your people', 'Explore events near you, save your favourites, and reserve a place.'], ['Make it a memory', 'Show up, feel the energy, and come back for your next experience.']].map(([title, copy], index) => <li key={title}><span>0{index + 1}</span><div><h3>{title}</h3><p>{copy}</p></div></li>)}</ol><CommunityLink className="vf-button" to="/signup">Join the community <ArrowUpRight size={19} /></CommunityLink></div></section>
      <section className="vf-cta"><span className="vf-eyebrow"><Sparkles size={16} /> YOUR PEOPLE ARE OUT THERE</span><h2>Find your people.<br /><em>Feel like you belong.</em></h2><p>A whole world of experiences. One community to call your own.</p><CommunityLink className="vf-button vf-lime" to="/signup">Become a Vibfy member <ArrowUpRight size={19} /></CommunityLink><span className="vf-cta-note"><Check size={15} /> One account. Your whole Vibfy.</span></section>
    </main><CommunityFooter />
  </div>
}
